"""Phase 0 source audit: does each feed parse, and do its pages extract? Writes a markdown table."""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from .config import Settings
from .extract import extract_page
from .ingest import Fetcher, parse_feed
from .urls import canonicalize


def audit_source(fetcher: Fetcher, source: dict, sample: int = 3) -> dict:
    row = {"id": source["id"], "outlet": source["outlet"], "leaning": source["leaning"], "feed_url": source["feed_url"],
           "status": "ok", "entries": 0, "fresh": 0, "per_day": None, "sampled": 0, "body_ok": 0, "image_ok": 0, "date_ok": 0,
           "wire": 0, "redirected": 0, "median_chars": 0, "error": None, "used_url": None}
    try:
        entries = parse_feed(fetcher, source["feed_url"], source.get("alt_feed_urls"))
        row["used_url"] = getattr(parse_feed, "used_url", None)
        if row["used_url"] and row["used_url"] != source["feed_url"]:
            row["error"] = f"WORKED VIA ALT URL {row['used_url']}"
    except Exception as exc:
        row.update(status="FEED_FAIL", error=str(exc)[:300])
        return row
    row["entries"] = len(entries)
    cutoff = datetime.now(timezone.utc) - timedelta(hours=72)
    row["fresh"] = sum(1 for e in entries if e["published_at"] is None or e["published_at"] >= cutoff)
    dated = sorted([e["published_at"] for e in entries if e["published_at"]])
    if len(dated) >= 2:
        span_days = max((dated[-1] - dated[0]).total_seconds() / 86400, 1 / 24)
        row["per_day"] = round(len(dated) / span_days, 1)
    chars = []
    for entry in entries[:sample]:
        row["sampled"] += 1
        try:
            resp = fetcher.get(entry["link"])
            page = extract_page(resp.text, str(resp.url))
        except Exception as exc:
            row["error"] = (row["error"] or "") + f" page: {str(exc)[-60:]}"
            continue
        n = len(page.get("text") or "")
        chars.append(n)
        row["body_ok"] += n >= 500
        row["image_ok"] += bool(page.get("image") or entry.get("image_url"))
        row["date_ok"] += bool(page.get("published_at") or entry.get("published_at"))
        row["wire"] += bool(page.get("wire_hint"))
        row["redirected"] += canonicalize(str(resp.url)) != canonicalize(entry["link"])
    if chars:
        chars.sort()
        row["median_chars"] = chars[len(chars) // 2]
    if row["sampled"] and row["body_ok"] == 0:
        row["status"] = "NO_BODY"
    elif row["entries"] == 0:
        row["status"] = "EMPTY"
    return row


def render_markdown(rows: list[dict]) -> str:
    lines = [f"# Source audit — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", "",
             "Generated by `python -m pipeline.cli verify-feeds`. Sample = first 3 entries per feed.", "",
             "| id | outlet | leaning | status | entries | fresh≤72h | est/day | body ok | image ok | date ok | wire | redirect | median chars | error |",
             "|---|---|---|---|---:|---:|---:|---|---|---|---|---|---:|---|"]
    for r in rows:
        s = r["sampled"] or 0
        lines.append(
            f"| {r['id']} | {r['outlet']} | {r['leaning']} | {r['status']} | {r['entries']} | {r['fresh']} | {r['per_day'] if r['per_day'] is not None else '-'} | "
            f"{r['body_ok']}/{s} | {r['image_ok']}/{s} | {r['date_ok']}/{s} | {r['wire']}/{s} | {r['redirected']}/{s} | {r['median_chars']} | {(r['error'] or '')[:160]} |"
        )
    ok = [r for r in rows if r["status"] == "ok"]
    lines += ["", f"**{len(ok)}/{len(rows)} feeds passing.** Mark passing feeds `verified: true` in `sources.yaml`; fix or disable the rest.", ""]
    return "\n".join(lines)


def run_audit(settings: Settings, sources: list[dict], out_path: str | None, only: str | None = None) -> list[dict]:
    fetcher = Fetcher(settings)
    print(f"[audit] fetcher: {'curl_cffi impersonate=' + settings.fetch_impersonate if fetcher.impersonating else 'requests'}")
    rows = []
    for source in sources:
        if only and source["id"] != only and source["outlet"].lower() != only.lower():
            continue
        row = audit_source(fetcher, source)
        rows.append(row)
        print(f"[audit] {row['id']:<32} {row['status']:<9} entries={row['entries']:<3} fresh={row['fresh']:<3} body={row['body_ok']}/{row['sampled']} img={row['image_ok']}/{row['sampled']} date={row['date_ok']}/{row['sampled']} wire={row['wire']}/{row['sampled']} {row['error'] or ''}")
    md = render_markdown(rows)
    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(md, encoding="utf-8")
        print(f"[audit] wrote {out_path}")
    return rows
